WorkDayTimer/Models/ErrorViewModel.cs
using System;

namespace WorkDayTimerWebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WorkDayTimer/Models/WorkDayTimer.cs
using Microsoft.AspNetCore.Identity;
using System;
using System.ComponentModel.DataAnnotations;

namespace WorkDayTimerWebApp.Models
{
    public class WorkDayTimer
    {
        [Key]
        public int Id { get; set; }
        public string UserId { get; set; }
        public IdentityUser User { get; set; }

        [Required]
        [DataType(DataType.Text)]
        public string Name { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd}")]
        public DateTime Date { get; set; }

        [Range(0, 24)]
        public int WorkDayHours { get; set; }

        [DataType(DataType.Duration)]
        public DateTime TimerTime { get; set; }

        public bool IsRunning { get; set; }

        [Range(0, 24)]
        public int MaxTimerCount { get; set; }

    }
}

WorkDayTimer/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using WorkDayTimerWebApp.Models;

namespace WorkDayTimerWebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WorkDayTimer/Controllers/WorkDayTimersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WorkDayTimerWebApp.Data;
using WorkDayTimerWebApp.Models;

namespace WorkDayTimerWebApp.Controllers
{
    public class WorkDayTimersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public WorkDayTimersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: WorkDayTimers
        public async Task<IActionResult> Index()
        {
            var applicationDbContext = _context.WorkDayTimers.Include(w => w.User);
            return View(await applicationDbContext.ToListAsync());
        }

        // GET: WorkDayTimers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var workDayTimer = await _context.WorkDayTimers
                .Include(w => w.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (workDayTimer == null)
            {
                return NotFound();
            }

            return View(workDayTimer);
        }

        // GET: WorkDayTimers/Create
        public IActionResult Create()
        {
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id");
            return View();
        }

        // POST: WorkDayTimers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,UserId,Name,Date,WorkDayHours,TimerTime,IsRunning,MaxTimerCount")] WorkDayTimer workDayTimer)
        {
            if (ModelState.IsValid)
            {
                _context.Add(workDayTimer);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", workDayTimer.UserId);
            return View(workDayTimer);
        }

        // GET: WorkDayTimers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var workDayTimer = await _context.WorkDayTimers.FindAsync(id);
            if (workDayTimer == null)
            {
                return NotFound();
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", workDayTimer.UserId);
            return View(workDayTimer);
        }

        // POST: WorkDayTimers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,UserId,Name,Date,WorkDayHours,TimerTime,IsRunning,MaxTimerCount")] WorkDayTimer workDayTimer)
        {
            if (id != workDayTimer.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(workDayTimer);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!WorkDayTimerExists(workDayTimer.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["UserId"] = new SelectList(_context.Users, "Id", "Id", workDayTimer.UserId);
            return View(workDayTimer);
        }

        // GET: WorkDayTimers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var workDayTimer = await _context.WorkDayTimers
                .Include(w => w.User)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (workDayTimer == null)
            {
                return NotFound();
            }

            return View(workDayTimer);
        }

        // POST: WorkDayTimers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var workDayTimer = await _context.WorkDayTimers.FindAsync(id);
            _context.WorkDayTimers.Remove(workDayTimer);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool WorkDayTimerExists(int id)
        {
            return _context.WorkDayTimers.Any(e => e.Id == id);
        }
    }
}

WorkDayTimer/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WorkDayTimer/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WorkDayTimerWebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WorkDayTimerWebApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="WorkDayTimers" asp-action="Index">WorkDayTimers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - WorkDayTimerWebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

WorkDayTimer/Views/WorkDayTimers/Create.cshtml
@model WorkDayTimerWebApp.Models.WorkDayTimer

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>WorkDayTimer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class ="form-control" asp-items="ViewBag.UserId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WorkDayHours" class="control-label"></label>
                <input asp-for="WorkDayHours" class="form-control" />
                <span asp-validation-for="WorkDayHours" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TimerTime" class="control-label"></label>
                <input asp-for="TimerTime" class="form-control" />
                <span asp-validation-for="TimerTime" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsRunning" /> @Html.DisplayNameFor(model => model.IsRunning)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="MaxTimerCount" class="control-label"></label>
                <input asp-for="MaxTimerCount" class="form-control" />
                <span asp-validation-for="MaxTimerCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WorkDayTimer/Views/WorkDayTimers/Delete.cshtml
@model WorkDayTimerWebApp.Models.WorkDayTimer

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>WorkDayTimer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Id)
        </dd class>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WorkDayHours)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WorkDayHours)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TimerTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TimerTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsRunning)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsRunning)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaxTimerCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaxTimerCount)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WorkDayTimer/Views/WorkDayTimers/Details.cshtml
@model WorkDayTimerWebApp.Models.WorkDayTimer

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>WorkDayTimer</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.User)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.User.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Date)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Date)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.WorkDayHours)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.WorkDayHours)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TimerTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TimerTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsRunning)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsRunning)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MaxTimerCount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MaxTimerCount)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

WorkDayTimer/Views/WorkDayTimers/Edit.cshtml
@model WorkDayTimerWebApp.Models.WorkDayTimer

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>WorkDayTimer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="UserId" class="control-label"></label>
                <select asp-for="UserId" class="form-control" asp-items="ViewBag.UserId"></select>
                <span asp-validation-for="UserId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Date" class="control-label"></label>
                <input asp-for="Date" class="form-control" />
                <span asp-validation-for="Date" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="WorkDayHours" class="control-label"></label>
                <input asp-for="WorkDayHours" class="form-control" />
                <span asp-validation-for="WorkDayHours" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TimerTime" class="control-label"></label>
                <input asp-for="TimerTime" class="form-control" />
                <span asp-validation-for="TimerTime" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
                <label class="form-check-label">
                    <input class="form-check-input" asp-for="IsRunning" /> @Html.DisplayNameFor(model => model.IsRunning)
                </label>
            </div>
            <div class="form-group">
                <label asp-for="MaxTimerCount" class="control-label"></label>
                <input asp-for="MaxTimerCount" class="form-control" />
                <span asp-validation-for="MaxTimerCount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WorkDayTimer/Views/WorkDayTimers/Index.cshtml
@model IEnumerable<WorkDayTimerWebApp.Models.WorkDayTimer>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.User)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Date)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.WorkDayHours)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TimerTime)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IsRunning)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.MaxTimerCount)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.User.Id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Date)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.WorkDayHours)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TimerTime)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.IsRunning)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MaxTimerCount)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>